version: "3"
services:
  app:
    container_name: docker-node-ostrom
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/Activity
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
